<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by IcoMoon.io -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="17" height="17" viewBox="0 0 17 17">
<g>
</g>
	<path d="M2 14h13v-11h-13v11zM3 4h11v9h-11v-9z" fill="#000000" />
	<path d="M16 4.531h1v7.938h-1v-7.938z" fill="#000000" />
	<path d="M0 4.531h1v7.938h-1v-7.938z" fill="#000000" />
</svg>
