# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chat_server_grpc_pb2 as chat__server__grpc__pb2


class ChatServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Communicate = channel.unary_unary(
        '/chat_server_grpc.ChatServer/Communicate',
        request_serializer=chat__server__grpc__pb2.Request.SerializeToString,
        response_deserializer=chat__server__grpc__pb2.Response.FromString,
        )


class ChatServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Communicate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChatServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Communicate': grpc.unary_unary_rpc_method_handler(
          servicer.Communicate,
          request_deserializer=chat__server__grpc__pb2.Request.FromString,
          response_serializer=chat__server__grpc__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'chat_server_grpc.ChatServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
