<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by IcoMoon.io -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="17" height="17" viewBox="0 0 17 17">
<g>
</g>
	<path d="M10 4h5.826v1h-5.826v-1z" fill="#000000" />
	<path d="M10 7.996h3.497v1h-3.497v-1z" fill="#000000" />
	<path d="M10.009 5.998h6.991v1h-6.991v-1z" fill="#000000" />
	<path d="M10 9.993h6.991v1h-6.991v-1z" fill="#000000" />
	<path d="M10 12h5.826v1h-5.826v-1z" fill="#000000" />
	<path d="M0 13h9v-9h-9v9zM1 5h7v7h-7v-7z" fill="#000000" />
</svg>
