import json
import os
import re
import subprocess
import requests
TOKEN = os.environ["GITHUB_TOKEN"]
REPO = os.environ["REPO"]
PR_NUMBER = os.environ["PR_NUMBER"]
BASE = os.environ["BASE_REF"]
HEAD = os.environ["HEAD_REF"]
headers = {
"Authorization": f"Bearer {TOKEN}",
"Accept": "application/vnd.github+json"
}
# Files changed
files = subprocess.check_output(
["git", "diff", "--name-only", BASE, HEAD],
text=True
).splitlines()
# Diff statistics
diff_stat = subprocess.check_output(
["git", "diff", "--stat", BASE, HEAD],
text=True
)
# Added / Removed lines
diff = subprocess.check_output(
["git", "diff", BASE, HEAD],
text=True
)
added = 0
removed = 0
for line in diff.splitlines():
if line.startswith("+") and not line.startswith("+++"):
added += 1
elif line.startswith("-") and not line.startswith("---"):
removed += 1
# Search TODO / FIXME
todos = []
for file in files:
if os.path.isfile(file):
with open(file, "r", encoding="utf-8", errors="ignore") as f:
for num, line in enumerate(f, start=1):
if re.search(r"TODO|FIXME", line):
todos.append(f"{file}:{num} → {line.strip()}")
todo_text = "\n".join(todos) if todos else "No TODO/FIXME found."
# Markdown table
table = "| Metric | Value |\n"
table += "|--------|-------|\n"
table += f"| Files Changed | {len(files)} |\n"
table += f"| Lines Added | {added} |\n"
table += f"| Lines Removed | {removed} |\n"
comment_body = f"""
##  Automated PR Review
### Summary
{table}
### TODO / FIXME Scan
```
{todo_text}
```
### Diff Statistics
```
{diff_stat}
```
---
*Automatically generated by GitHub Actions*
"""
comments_url = (
f"https://api.github.com/repos/{REPO}/issues/{PR_NUMBER}/comments"
)
comments = requests.get(
comments_url,
headers=headers
).json()
existing_comment = None
for comment in comments:
if "Automated PR Review" in comment["body"]:
existing_comment = comment["id"]
break
if existing_comment:
requests.patch(
f"https://api.github.com/repos/{REPO}/issues/comments/{existing_comment}",
headers=headers,
json={"body": comment_body}
)
else:
requests.post(
comments_url,
headers=headers,
json={"body": comment_body}
)
print("Review comment updated successfully")
