<Project Sdk="MSTest.Sdk/4.3.0">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AppxGeneratePriEnabled>false</AppxGeneratePriEnabled>
    <IncludeProjectPriFile>false</IncludeProjectPriFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AutoHotspot\AutoHotspot.csproj" />
  </ItemGroup>
</Project>
