name: PR Review Bot

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Get changed files
        id: files
        uses: tj-actions/changed-files@v39

      - name: Review changed files
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const allowedFiles = [
              "Contributors.md",
              "README.md",
              "docs/",
              "translations/",
              ".github/ISSUE_TEMPLATE"
            ];

            const changedFiles = `\`${{ steps.files.outputs.all_changed_files }}\``.split(" ");

            const invalidFiles = changedFiles.filter(file =>
              !allowedFiles.some(allowed => file.startsWith(allowed))
            );

            let message = "";

            if (invalidFiles.length > 0) {
              message = [
                "👋 Hi there! Thanks for your contribution!  ",
                "",
                "I noticed your PR includes changes outside the usual allowed files for first-time contributors:  ",
                "",
                "**Changed files:**  ",
                ...invalidFiles.map(f => `- ${f}`),
                "",
                "Please review the contribution guidelines and ensure only the intended files are modified. 😊"
              ].join("\n");
            } else {
              message = [
                "✅ Thank you for following the contribution guidelines! 🎉  ",
                "Your PR looks great and only modifies the intended files."
              ].join("\n");
            }

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
